"""initial schema

Revision ID: 4c67766feb30
Revises: 
Create Date: 2026-06-30 14:28:07.211059
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4c67766feb30'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gh_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repo_gh_repo_id'), ['gh_repo_id'], unique=True)

    op.create_table('code_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_chunk', schema=None) as batch_op:
        batch_op.create_index('ix_code_chunk_repo', ['repo_id'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('gh_issue_number', sa.BigInteger(), nullable=True),
    sa.Column('trigger', sa.Enum('webhook', 'manual', 'eval', name='jobtrigger', native_enum=False), nullable=False),
    sa.Column('issue_title', sa.Text(), nullable=True),
    sa.Column('issue_body_ref', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('queued', 'running', 'awaiting_approval', 'approved', 'rejected', 'done', 'failed', name='jobstate', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('budget', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cost', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'gh_issue_number', 'state', name='uq_job_repo_issue_state')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_repo_state', ['repo_id', 'state'], unique=False)

    op.create_table('approval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='approvaldecision', native_enum=False), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_source', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index('ix_approval_job', ['job_id'], unique=False)

    op.create_table('run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('reproduce', 'localize', 'fix', 'verify', name='runphase', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ok', 'fail', 'error', name='runstatus', native_enum=False), nullable=False),
    sa.Column('langfuse_trace_id', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index('ix_run_job_attempt', ['job_id', 'attempt'], unique=False)

    op.create_table('artifact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('diff', 'test_output', 'stacktrace', 'log', 'reasoning', 'issue_body', name='artifactkind', native_enum=False), nullable=False),
    sa.Column('storage', sa.Enum('inline_small', 'blob_ref', name='artifactstorage', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('blob_url', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_job_kind', ['job_id', 'kind'], unique=False)

    op.create_table('fix',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('diff_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('reasoning_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('diff_lines_added', sa.Integer(), nullable=False),
    sa.Column('diff_lines_removed', sa.Integer(), nullable=False),
    sa.Column('wrote_repro_test', sa.Boolean(), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tests_pass', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['diff_artifact_id'], ['artifact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reasoning_artifact_id'], ['artifact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fix')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index('ix_artifact_job_kind')

    op.drop_table('artifact')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index('ix_run_job_attempt')

    op.drop_table('run')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_job')

    op.drop_table('approval')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_repo_state')

    op.drop_table('job')
    with op.batch_alter_table('code_chunk', schema=None) as batch_op:
        batch_op.drop_index('ix_code_chunk_repo')

    op.drop_table('code_chunk')
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_gh_repo_id'))
        batch_op.drop_index(batch_op.f('ix_repo_full_name'))

    op.drop_table('repo')
    # ### end Alembic commands ###
